type UserActionTypes = 
"USER_SET_IS_USER_RECALL_COMPLETE" | 
"USER_RECALL_USER" |
"USER_LOGIN" | 
"USER_SET_IS_USER_AUTHORIZED" | 
"USER_SET_IS_USER_AUTHORIZING" | 
"USER_SET_USER_AUTHORIZATION_ERROR" |
"USER_SET_USER_CREATION_ERROR" |
"USER_SET_USER_ALIAS" |
"USER_LOGOUT" |
"USER_CREATE" |
"USER_SET_USER_IS_BEING_CREATED"|
"USER_RESET"


export type ActionTypes = UserActionTypes